### ISSUE TITLE
Error running the README instructions

### ISSUE THREAD

**Issue by Ramarti** [tokenspice/tokenspice#143] opened 2022-02-04 16:21 UTC
Once I reach 

`pytest sol057/contracts/simpletoken/test/test_Simpletoken.py::test_transfer`

I see this:

```
(venv) (base) ➜  tokenspice git:(main) pytest sol057/contracts/simpletoken/test/test_Simpletoken.py::test_transfer

Compiling contracts...
  Solc version: 0.7.6
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

contracts/Greeter.sol:4:1: ParserError: Source "hardhat/console.sol" not found: File outside of allowed directories.
import "hardhat/console.sol";
^---------------------------^


ERROR: Unable to load project

```

Seems like the example contract is copypasted from Hardhat, but console.sol is not there because TokenSPICE uses Ganache?

**Comment by trentmc** [comment] 2022-02-04 22:25
Towards reproducing the error, I just did a clean install of TokenSPICE, and went through the README until (and including) the line
```
pytest sol057/contracts/simpletoken/test/test_Simpletoken.py::test_transfer
```

It successfully completed.

So then I dug more.

The problem that was reported:
```
contracts/Greeter.sol:4:1: ParserError: Source "hardhat/console.sol" not found: File outside of allowed directories.
import "hardhat/console.sol";
```

However, TokenSPICE does not _have_ a contract named `Greeter.sol`, let alone lines inside that import `hardhat/console.sol`. We can verify this by running the following. Both commands return 0 hits.
```console
(venv) trentmc@trentmcLnv:~/code/tokenspice$ find . -name Greeter.sol
(venv) trentmc@trentmcLnv:~/code/tokenspice$ grep -r "hardhat/console.sol"
(venv) trentmc@trentmcLnv:~/code/tokenspice$
```

A possible issue: you may not have an up-to-date version of TokenSPICE and you have a parallel `contracts` directory. To fix, just update to the most recent TokenSPICE (eg `git pull`).

Details: 
- the location of `contracts` looks a bit fishy, it's in a root directory, not a subdirectory like `sol057/contracts`. This is an issue because Brownie will try to look at other directories named `contracts` that are siblings of the `tokenspice` directory. 
- It's already been fixed in TokenSPICE in Nov 2021 or so. How: I moved the `contracts` directory (not plural) to subdirectories, and the problem goes away. So just update your TokenSPICE (git pull) and you should be ok too.

Please let me know how it goes.

**Closed** 2022-02-07 14:19 UTC
